baseURL = "https://nevstokes.com/"
languageCode = "en-gb"
title = "nevstokes.com"
theme = "pure"
# theme = "beautifulhugo"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe= true

[Params]
  subtitle = "Random musings of a child progeny"
  dateFormat = "Monday, January 2, 2006"
  rss = true
  readingTime = true
  disableNextPrev = true

[Author]
  name = "Nev Stokes"
  twitter = "nevstokes"
  linkedin = "nevstokes"
  github = "nevstokes"
  stackoverflow = "users/224639/nev-stokes"
  keybase = "nevstokes"
  strava = "nevstokes"

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 1

[[menu.main]]
    name = "About Me"
    url = "page/about-me/"
    weight = 2

[[menu.main]]
    name = "Accessibility"
    url = "page/accessibility/"
    weight = 3

[[menu.main]]
    name = "Colophon"
    url = "page/colophon/"
    weight = 4
